### ISSUE TITLE
[1.11.2 0.1-5] crashes client on startup

### ISSUE THREAD

**Issue by kreezxil** [rockhymas/strait#3]
https://gist.github.com/kreezxil/a77bfc45f2d7c39fd2915ab8749d0126

**Comment by starg09** [comment]
Can confirm: same crash on 0.1-6, tested on both Forge 2236 and 2251

http://paste.feed-the-beast.com/view/cb337598

**Comment by rockhymas** [comment]
Sorry about that, looks like I accidentally published a deobfuscated build of the mod. Working on updating it now.

**Comment by rockhymas** [comment]
Should be fixed in version 0.2, for MC 1.9, 1.10, and 1.11. Thanks for reporting it!
