### ISSUE TITLE
Crash on right click

### ISSUE THREAD

**Issue by tyra314** [rockhymas/strait#4]
I get the following crash when right-clicked a bed

https://gist.github.com/tyra314/4b0dda9eb159edf195088eb5ddcb002a

Forge 2251
strait-0.1-6

**Comment by getBoolean** [comment]
I crashed when I right clicked to place a sapling 
Most likely it is any right click
[crash-2017-02-24_18.18.48-client.txt](https://github.com/rockhymas/strait/files/800770/crash-2017-02-24_18.18.48-client.txt)

**Comment by rockhymas** [comment]
Sorry about that, looks like I accidentally published a deobfuscated build of the mod. Working on updating it now.

**Comment by rockhymas** [comment]
Should be fixed in version 0.2, for MC 1.9, 1.10, and 1.11. Thanks for reporting it!
